dist: trusty
language: java
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
before_deploy:
- echo "deploying ${RELEASE_FILE} to GitHub releases"
deploy:
  provider: releases
  api_key: ${GITHUB_API_TOKEN}
  file_glob: true
  file: "${RELEASE_FILE}"
  skip_cleanup: true
  draft: true
  on:
    repo: LemADEC/WarpDrive
    branch: MC1.12
    tags: true
    jdk: oraclejdk8
after_success:
- export RELEASE_FILE=$(ls output/*.jar)
